
import Navbar from "@/components/layout/Navbar";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Loader from "@/components/ui/Loader";
import ClientScripts from "@/components/layout/ClientScripts";
import Head from "next/head";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="preload"
          as="style"
          href="./globals.css"
        />
      </Head>
      <body className="min-h-screen flex flex-col">
        <Navbar />
        <main className="flex-1">
          {children}
          <Loader />
        </main>
        <Footer />
        <ClientScripts />
      </body>
    </html>
  );
}
